export const folderImagesStyles = {
    container: {
      position: "relative",
      minHeight: "100vh",
      py: 8,
      mb: 8,
    },
    background: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundImage: `url('/placeholder.svg?height=1080&width=1920')`,
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundAttachment: "fixed",
      zIndex: -2,
      filter: "brightness(0.9)",
    },
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: `linear-gradient(135deg, rgba(245, 169, 184, 0.7) 0%, rgba(169, 222, 245, 0.7) 100%)`,
      zIndex: -1,
    },
    loadingContainer: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      height: "70vh",
      gap: 2,
      position: "relative",
    },
    dialogPaper: {
      borderRadius: 4,
      width: "100%",
      maxWidth: "500px",
      background: "rgba(255, 255, 255, 0.95)",
      backdropFilter: "blur(10px)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.2)",
  },
    loadingContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    loadingIcon: {
      animation: "iconRotate 2s infinite linear",
      "@keyframes iconRotate": {
        "0%": {
          transform: "rotateY(0deg)",
        },
        "100%": {
          transform: "rotateY(540deg)",
        },
      },
      mb: 2,
    },
    errorAlert: {
      borderRadius: 2,
      background: "rgba(211, 47, 47, 0.8)",
      color: "white",
    },
    headerPaper: {
      p: 4,
      borderRadius: 4,
      position: "relative",
      mb: 4,
      background: "rgba(255, 255, 255, 0.15)",
      backdropFilter: "blur(10px)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    },
    headerContent: {
      display: "flex",
      alignItems: "center",
      mb: 2,
    },
    title: {
      fontWeight: "bold",
      color: "white",
    },
    addButton: {
      position: "absolute",
      top: 16,
      right: 16,
      background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
      boxShadow: "0 4px 12px rgba(255, 117, 140, 0.3)",
    },
    uploaderContainer: {
      maxWidth: 600,
      mx: "auto",
      my: 4,
    },
    emptyAlbum: {
      textAlign: "center",
      py: 8,
      borderRadius: 4,
      background: "rgba(255, 255, 255, 0.15)",
      backdropFilter: "blur(10px)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
      mb: 8,
      mx: "auto",
      width: "100%",
      maxWidth: "900px",
    },
    emptyAlbumIcon: {
      fontSize: 100,
      color: "rgba(255, 255, 255, 0.7)",
      mb: 2,
    },
    emptyAlbumTitle: {
      color: "white",
      fontWeight: "bold",
    },
    emptyAlbumText: {
      color: "white",
      mb: 4,
      opacity: 0.9,
      maxWidth: "600px",
      mx: "auto",
    },
    uploadButton: {
      mt: 2,
      borderRadius: 2,
      py: 1.5,
      px: 4,
      background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
      boxShadow: "0 4px 12px rgba(255, 117, 140, 0.3)",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      "&:hover": {
        transform: "translateY(-3px)",
        boxShadow: "0 6px 16px rgba(255, 117, 140, 0.4)",
      },
    },
    backButton: {
        position: "absolute",
        top: -60,
        right: 0,
        color: "white",
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        backdropFilter: "blur(10px)",
        "&:hover": {
          backgroundColor: "rgba(255, 255, 255, 0.3)",
        },
      },
  }
  