export const folderListStyles = {
    container: {
        position: "relative",
        minHeight: "100vh",
        py: 8,
        mb: 8,
    },
    background: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundImage: `url('/placeholder.svg?height=1080&width=1920')`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundAttachment: "fixed",
        zIndex: -2,
        filter: "brightness(0.9)",
    },
    overlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: `linear-gradient(135deg, rgba(245, 169, 184, 0.7) 0%, rgba(169, 222, 245, 0.7) 100%)`,
        zIndex: -1,
    },
    contentContainer: {
        position: "relative",
        zIndex: 1,
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        mb: 4,
        p: 3,
        borderRadius: 4,
        background: `linear-gradient(135deg, rgba(245, 169, 184, 0.7) 0%, rgba(169, 222, 245, 0.7) 100%)`,
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.2)",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    },
    addButton: {
        borderRadius: 2,
        background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
        boxShadow: "0 4px 12px rgba(255, 117, 140, 0.3)",
        transition: "transform 0.3s ease, box-shadow 0.3s ease",
        "&:hover": {
            transform: "translateY(-3px)",
            boxShadow: "0 6px 16px rgba(255, 117, 140, 0.4)",
        },
    },
    loadingContainer: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "70vh",
    },
    errorAlert: {
        borderRadius: 2,
        boxShadow: "0 4px 12px rgba(211, 47, 47, 0.2)",
        backgroundColor: "rgba(211, 47, 47, 0.8)",
        color: "white",
    },
    emptyState: {
        p: 6,
        textAlign: "center",
        borderRadius: 4,
        background: "rgba(255, 255, 255, 0.85)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.2)",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
    },
    emptyStateIcon: {
        fontSize: 80,
        color: "#ff758c",
        mb: 2,
    },
    emptyStateText: {
        mb: 4,
    },
    createFirstAlbumButton: {
        borderRadius: 2,
        background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
        boxShadow: "0 4px 12px rgba(255, 117, 140, 0.3)",
        transition: "transform 0.3s ease, box-shadow 0.3s ease",
        "&:hover": {
            transform: "translateY(-3px)",
            boxShadow: "0 6px 16px rgba(255, 117, 140, 0.4)",
        },
    },
    folderItem: {
        cursor: "pointer",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        transition: "all 0.3s ease",
        "&:hover": {
            transform: "translateY(-10px)",
        },
    },
    folderIcon: {
        fontSize: 100,
    },
    folderTitle: {
        fontWeight: "bold",
        color: "#333",
        textAlign: "center",
        maxWidth: 200,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    folderDescription: {
        color: "#555",
        textAlign: "center",
        maxWidth: 200,
        overflow: "hidden",
        textOverflow: "ellipsis",
        display: "-webkit-box",
        WebkitLineClamp: 2,
        WebkitBoxOrient: "vertical",
        height: 40,
        mb: 1,
    },
    actionButtons: {
        display: "flex",
        gap: 1,
        mt: 1,
    },
    editButton: {
        bgcolor: "rgba(255, 255, 255, 0.9)",
        color: "#ff758c",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        "&:hover": { bgcolor: "white" },
    },
    deleteButton: {
        bgcolor: "rgba(255, 255, 255, 0.9)",
        color: "#ff758c",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        "&:hover": { bgcolor: "white" },
    },
    dialogPaper: {
        borderRadius: 4,
        width: "100%",
        maxWidth: "500px",
        background: "rgba(255, 255, 255, 0.95)",
        backdropFilter: "blur(10px)",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.2)",
    },
    dialogTitle: {
        pr: 6,
        color: "#333",
    },
    closeButton: {
        position: "absolute",
        right: 8,
        top: 8,
        color: "#ff758c",
    },
    titleField: {
        mb: 2,
    },
    inputProps: {
        borderRadius: 2,
        color: "#333",
    },
    inputLabelProps: {
        color: "#555",
        "&.MuiInputLabel-shrink": {
            transform: "translate(14px, -9px) scale(0.75)",
            background: "white",
            padding: "0 5px",
        },
    },
    dialogActions: {
        p: 3,
    },
    cancelButton: {
        borderRadius: 2,
    },
    saveButton: {
        borderRadius: 2,
        background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
    },
    mobileFab: {
        position: "fixed",
        bottom: 76,
        right: 16,
        display: { sm: "none" },
    },
    fab: {
        background: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
        boxShadow: "0 4px 12px rgba(255, 117, 140, 0.3)",
    },
}
