export const homePageStyles = {
    container: {
      position: "relative",
      minHeight: "100vh",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
    },
    background: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundImage: `url('/placeholder.svg?height=1080&width=1920')`,
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundAttachment: "fixed",
      zIndex: -2,
      filter: "brightness(0.9)",
    },
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: `linear-gradient(135deg, rgba(245, 169, 184, 0.7) 0%, rgba(169, 222, 245, 0.7) 100%)`,
      zIndex: -1,
    },
    decorElement1: {
      position: "absolute",
      top: "5%",
      left: "5%",
      width: "150px",
      height: "150px",
      backgroundImage: `url('/placeholder.svg?height=150&width=150')`,
      backgroundSize: "contain",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
      opacity: 0.6,
      zIndex: 0,
    },
    decorElement2: {
      position: "absolute",
      bottom: "5%",
      right: "5%",
      width: "180px",
      height: "180px",
      backgroundImage: `url('/placeholder.svg?height=180&width=180')`,
      backgroundSize: "contain",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
      opacity: 0.6,
      zIndex: 0,
      transform: "rotate(180deg)",
    },
    heroContainer: {
      position: "relative",
      zIndex: 1,
      py: 8,
    },
    heroContent: {
      display: "flex",
      flexDirection: { xs: "column", md: "row" },
      alignItems: "center",
      justifyContent: "space-between",
      gap: 4,
      mb: 6,
    },
    heroTextContent: {
      flex: 1,
      textAlign: { xs: "center", md: "left" },
    },
    heroTitle: {
      fontWeight: 800,
      fontSize: { xs: "2.5rem", sm: "3.5rem", md: "4rem" },
      color: "#333",
      mb: 2,
      textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
      position: "relative",
      display: "inline-block",
    },
    heroTitleUnderline: {
      position: "absolute",
      bottom: -10,
      left: 0,
      width: "80%",
      height: "6px",
      background: "linear-gradient(90deg, #ff758c 0%, #a9def5 100%)",
      borderRadius: "3px",
    },
    heroSubtitle: {
      color: "#555",
      mb: 4,
      maxWidth: "600px",
      mx: { xs: "auto", md: 0 },
      fontWeight: 400,
    },
    heroButtons: {
      display: "flex",
      gap: 2,
      justifyContent: { xs: "center", md: "flex-start" },
      flexWrap: "wrap",
    },
    primaryButton: {
      borderRadius: 2,
      py: 1.5,
      px: 4,
      boxShadow: "0 10px 20px rgba(255, 117, 140, 0.3)",
      background: `linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)`,
      transition: "all 0.3s ease",
      "&:hover": {
        transform: "translateY(-5px)",
        boxShadow: "0 15px 25px rgba(255, 117, 140, 0.4)",
      },
    },
    secondaryButton: {
      borderRadius: 2,
      py: 1.5,
      px: 4,
      borderWidth: 2,
      borderColor: "#555",
      color: "#555",
      transition: "all 0.3s ease",
      "&:hover": {
        borderWidth: 2,
        borderColor: "#333",
        transform: "translateY(-5px)",
        boxShadow: "0 10px 20px rgba(0, 0, 0, 0.1)",
        backgroundColor: "rgba(255, 255, 255, 0.2)",
      },
    },
    heroImageContainer: {
      flex: 1,
      display: "flex",
      justifyContent: "center",
      position: "relative",
    },
    floatingAlbumContainer: {
      width: { xs: "280px", sm: "350px", md: "400px" },
      height: { xs: "280px", sm: "350px", md: "400px" },
      position: "relative",
      perspective: "1000px",
    },
    floatingAlbum1: {
      position: "absolute",
      width: "100%",
      height: "100%",
      borderRadius: "10px",
      background: "rgba(255, 255, 255, 0.8)",
      boxShadow: "0 20px 40px rgba(0, 0, 0, 0.2)",
      transform: "rotateY(-15deg) rotateX(5deg)",
      animation: "float 6s ease-in-out infinite",
      "@keyframes float": {
        "0%": {
          transform: "rotateY(-15deg) rotateX(5deg) translateY(0px)",
        },
        "50%": {
          transform: "rotateY(-10deg) rotateX(10deg) translateY(-20px)",
        },
        "100%": {
          transform: "rotateY(-15deg) rotateX(5deg) translateY(0px)",
        },
      },
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    floatingAlbumIcon1: {
      fontSize: { xs: "120px", sm: "150px", md: "180px" },
      color: "#ff758c",
      opacity: 0.8,
    },
    floatingAlbum2: {
      position: "absolute",
      width: "80%",
      height: "80%",
      borderRadius: "10px",
      background: "rgba(255, 255, 255, 0.9)",
      boxShadow: "0 15px 35px rgba(0, 0, 0, 0.2)",
      top: "10%",
      left: "-15%",
      transform: "rotateY(10deg) rotateX(-5deg)",
      animation: "float2 7s ease-in-out infinite",
      "@keyframes float2": {
        "0%": {
          transform: "rotateY(10deg) rotateX(-5deg) translateY(0px)",
        },
        "50%": {
          transform: "rotateY(15deg) rotateX(-10deg) translateY(-15px)",
        },
        "100%": {
          transform: "rotateY(10deg) rotateX(-5deg) translateY(0px)",
        },
      },
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      zIndex: -1,
    },
    floatingAlbumIcon2: {
      fontSize: { xs: "80px", sm: "100px", md: "120px" },
      color: "#a9def5",
      opacity: 0.8,
    },
    featuresSection: {
      mt: 10,
      position: "relative",
    },
    featuresTitle: {
      textAlign: "center",
      fontWeight: 700,
      color: "#333",
      mb: 6,
      position: "relative",
      display: "inline-block",
      left: "50%",
      transform: "translateX(-50%)",
    },
    featuresTitleUnderline: {
      position: "absolute",
      bottom: -5,
      left: 0,
      right: 0,
      height: "6px",
      background: "linear-gradient(90deg, #ff758c 0%, #a9def5 100%)",
      borderRadius: "3px",
      width: "60%",
      mx: "auto",
    },
    featuresContainer: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 3,
      mb: 8,
    },
    featureBox: {
      width: { xs: "100%", sm: "30%", md: "30%" },
      maxWidth: "300px",
      p: 3,
      borderRadius: "20px",
      background: "rgba(255, 255, 255, 0.85)",
      backdropFilter: "blur(10px)",
      boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      "&:hover": {
        transform: "translateY(-10px)",
        boxShadow: "0 15px 35px rgba(0, 0, 0, 0.15)",
      },
      position: "relative",
      overflow: "hidden",
    },
    featureHighlight: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "5px",
      background: "linear-gradient(90deg, #ff758c 0%, #ff7eb3 100%)",
    },
    featureHighlight2: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "5px",
      background: "linear-gradient(90deg, #a9def5 0%, #7fd6f7 100%)",
    },
    featureHighlight3: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "5px",
      background: "linear-gradient(90deg, #d4a5ff 0%, #b57dff 100%)",
    },
    featureIconContainer: {
      textAlign: "center",
      mb: 2,
    },
    featureIcon1: {
      fontSize: 50,
      color: "#ff758c",
    },
    featureIcon2: {
      fontSize: 50,
      color: "#a9def5",
    },
    featureIcon3: {
      fontSize: 50,
      color: "#d4a5ff",
    },
    featureTitle: {
      color: "#333",
      fontWeight: 600,
    },
    featureDescription: {
      color: "#555",
      variant: "body2",
    },
    ctaSection: {
      mt: 8,
      p: 6,
      borderRadius: "20px",
      background: "rgba(255, 255, 255, 0.85)",
      backdropFilter: "blur(10px)",
      boxShadow: "0 15px 50px rgba(0, 0, 0, 0.1)",
      textAlign: "center",
      position: "relative",
      overflow: "hidden",
    },
    ctaHighlight: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: "5px",
      background: "linear-gradient(90deg, #ff758c 0%, #a9def5 100%)",
    },
    ctaTitle: {
      color: "#333",
      fontWeight: "bold",
    },
    ctaDescription: {
      color: "#555",
      mb: 4,
      maxWidth: "800px",
      mx: "auto",
    },
    ctaButton: {
      borderRadius: "30px",
      py: 1.5,
      px: 6,
      background: `linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)`,
      boxShadow: "0 10px 20px rgba(255, 117, 140, 0.3)",
      transition: "all 0.3s ease",
      "&:hover": {
        transform: "translateY(-5px)",
        boxShadow: "0 15px 30px rgba(255, 117, 140, 0.4)",
      },
    },
  }
  